### Yanuar Gideon Simalango
#### 2009106014

In [2]:
import tensorflow as tf

#### Membuat tensor dengan shape(5,5) dengan nilai random

In [3]:
random_tensor = tf.random.normal([5,5],mean=0,stddev=1.0,seed=1)
random_tensor.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

#### Membuat tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima

In [4]:
prime_list = [[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53,59,61,67,71],[73,79,83,89,97]]
prime_tensor = tf.convert_to_tensor(prime_list, dtype=tf.float32)

print(prime_tensor)

tf.Tensor(
[[ 2.  3.  5.  7. 11.]
 [13. 17. 19. 23. 29.]
 [31. 37. 41. 43. 47.]
 [53. 59. 61. 67. 71.]
 [73. 79. 83. 89. 97.]], shape=(5, 5), dtype=float32)


#### Menampilkan hasil perhitungan aritmatika 2 variabel (5 operator)

In [12]:
#Penjumlahan
print(tf.add(random_tensor,prime_tensor))

tf.Tensor(
[[ 1.1886818  4.4845986  5.0653296  4.557296  11.099248 ]
 [13.591225  17.592823  16.877071  22.277103  28.94373  ]
 [31.643545  36.735676  42.856632  43.56784   46.617165 ]
 [51.514656  60.261772  60.974693  66.73537   72.532814 ]
 [71.25702   78.5621    82.43399   89.32067   98.13283  ]], shape=(5, 5), dtype=float32)


In [13]:
#Pengurangan
print(tf.subtract(random_tensor,prime_tensor))

tf.Tensor(
[[ -2.8113182  -1.5154012  -4.9346704  -9.442704  -10.900752 ]
 [-12.408775  -16.407177  -21.122929  -23.722897  -29.05627  ]
 [-30.356455  -37.264324  -39.143368  -42.43216   -47.382835 ]
 [-54.485344  -57.738228  -61.025307  -67.26463   -69.467186 ]
 [-74.74298   -79.4379    -83.56601   -88.67933   -95.86717  ]], shape=(5, 5), dtype=float32)


In [14]:
#Pembagian
print(tf.divide(random_tensor,prime_tensor))

tf.Tensor(
[[-4.0565911e-01  4.9486625e-01  1.3065875e-02 -3.4895775e-01
   9.0225823e-03]
 [ 4.5478795e-02  3.4871940e-02 -1.1173314e-01 -3.1430315e-02
  -1.9403580e-03]
 [ 2.0759510e-02 -7.1438937e-03  4.5283735e-02  1.3205621e-02
  -8.1454450e-03]
 [-2.8025346e-02  2.1385951e-02 -4.1485377e-04 -3.9496967e-03
   2.1588927e-02]
 [-2.3876399e-02 -5.5429488e-03 -6.8193977e-03  3.6030253e-03
   1.1678670e-02]], shape=(5, 5), dtype=float32)


In [15]:
#Perkalian
print(tf.multiply(random_tensor,prime_tensor))

tf.Tensor(
[[  -1.6226364     4.4537964     0.32664686  -17.09893       1.0917324 ]
 [   7.685916     10.077991    -40.335663    -16.626637     -1.6318411 ]
 [  19.949888     -9.77999      76.12196      24.417194    -17.993286  ]
 [ -78.7232       74.444496     -1.5436709   -17.73019     108.82978   ]
 [-127.237335    -34.593544    -46.97883      28.539564    109.884605  ]], shape=(5, 5), dtype=float32)


In [16]:
#Perpangkatan
print(tf.pow(random_tensor,prime_tensor))

tf.Tensor(
[[ 6.5823728e-01  3.2721055e+00  1.1899876e-06 -5.1891492e+02
   9.2036214e-12]
 [ 1.0783996e-03  1.3795117e-04 -1.6284565e+06 -5.7380047e-04
  -5.7294839e-37]
 [ 1.1639711e-06 -4.1596646e-22  1.0417667e+11  2.7025481e-11
  -2.5211261e-20]
 [-1.2788605e+09  9.0751462e+05 -0.0000000e+00 -0.0000000e+00
   1.4782479e+13]
 [-4.1142766e+17 -4.6565877e-29 -3.0507073e-21  0.0000000e+00
   1.7948009e+05]], shape=(5, 5), dtype=float32)


#### Menampilkan nilai maksimum dan minimal dari variabel random_tensor

In [17]:
#Max

max_1 = tf.argmax(random_tensor, axis=0)
max_2 = tf.argmax(random_tensor, axis=1)
print("Maksimum Menurut Kolom :",max_1.numpy())
print("Maksimum Menurut Baris :",max_2.numpy())

Maksimum Menurut Kolom : [2 0 2 2 3]
Maksimum Menurut Baris : [1 1 2 4 4]


In [20]:
#Min

min_1 = tf.argmin(random_tensor, axis=0)
min_2 = tf.argmin(random_tensor, axis=1)
print("Maksimum Menurut Kolom :",min_1.numpy())
print("Maksimum Menurut Baris :",min_2.numpy())

Maksimum Menurut Kolom : [4 4 1 0 2]
Maksimum Menurut Baris : [3 2 4 0 0]


#### Menampilkan hasil penggabungan variabel random_tensor dengan prime_tensor

In [21]:
print("Ukuran Data Asli:",random_tensor.shape,prime_tensor.shape)
concated_tensor = tf.concat([random_tensor,prime_tensor],axis=0)
print("Ukuran Data Setelah Penggabungan:",concated_tensor.shape)

Ukuran Data Asli: (5, 5) (5, 5)
Ukuran Data Setelah Penggabungan: (10, 5)


#### Menampilkan hasil sorting dari kedua variabel (desc)

In [28]:
#Random_tensor
sorted_r1 = tf.sort(random_tensor, direction="DESCENDING")
print("Hasil Sorting Desc:",sorted_r1.numpy())
sorted_r2 = tf.argsort(random_tensor,direction="DESCENDING")
print("Indexes dari Element Sorting Desc",sorted_r2.numpy())

Hasil Sorting Desc: [[ 1.4845988   0.0992484   0.06532937 -0.8113182  -2.4427042 ]
 [ 0.59282297  0.5912243  -0.05627038 -0.72289723 -2.1229296 ]
 [ 1.8566332   0.6435448   0.5678417  -0.26432407 -0.3828359 ]
 [ 1.5328138   1.2617711  -0.02530608 -0.2646297  -1.4853433 ]
 [ 1.132831    0.32066926 -0.43789294 -0.56601    -1.7429771 ]]
Indexes dari Element Sorting Desc [[1 4 2 0 3]
 [1 0 4 3 2]
 [2 0 3 1 4]
 [4 1 2 3 0]
 [4 3 1 2 0]]


In [30]:
#Prime_tensor

sorted_p1 = tf.sort(prime_tensor, direction="DESCENDING")
print("Hasil Sorting Desc:",sorted_p1.numpy())
sorted_p2 = tf.argsort(prime_tensor,direction="DESCENDING")
print("Indexes dari Element Sorting Desc:",sorted_p2.numpy())

Hasil Sorting Desc: [[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]]
Indexes dari Element Sorting Desc: [[4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]]


In [31]:
#Tensor Gabungan

print(concated_tensor)

tf.Tensor(
[[-8.1131822e-01  1.4845988e+00  6.5329373e-02 -2.4427042e+00
   9.9248402e-02]
 [ 5.9122431e-01  5.9282297e-01 -2.1229296e+00 -7.2289723e-01
  -5.6270380e-02]
 [ 6.4354479e-01 -2.6432407e-01  1.8566332e+00  5.6784171e-01
  -3.8283589e-01]
 [-1.4853433e+00  1.2617711e+00 -2.5306080e-02 -2.6462969e-01
   1.5328138e+00]
 [-1.7429771e+00 -4.3789294e-01 -5.6601000e-01  3.2066926e-01
   1.1328310e+00]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 1.3000000e+01  1.7000000e+01  1.9000000e+01  2.3000000e+01
   2.9000000e+01]
 [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  4.3000000e+01
   4.7000000e+01]
 [ 5.3000000e+01  5.9000000e+01  6.1000000e+01  6.7000000e+01
   7.1000000e+01]
 [ 7.3000000e+01  7.9000000e+01  8.3000000e+01  8.9000000e+01
   9.7000000e+01]], shape=(10, 5), dtype=float32)


In [32]:
sorted_c1 = tf.sort(concated_tensor, direction="DESCENDING")
print("Hasil Sorting Descensing:",sorted_c1.numpy())
sorted_c2 = tf.argsort(concated_tensor,direction="DESCENDING")
print("Indexes dari Element Sorting Descending:",sorted_c2.numpy())

Hasil Sorting Descensing: [[ 1.4845988e+00  9.9248402e-02  6.5329373e-02 -8.1131822e-01
  -2.4427042e+00]
 [ 5.9282297e-01  5.9122431e-01 -5.6270380e-02 -7.2289723e-01
  -2.1229296e+00]
 [ 1.8566332e+00  6.4354479e-01  5.6784171e-01 -2.6432407e-01
  -3.8283589e-01]
 [ 1.5328138e+00  1.2617711e+00 -2.5306080e-02 -2.6462969e-01
  -1.4853433e+00]
 [ 1.1328310e+00  3.2066926e-01 -4.3789294e-01 -5.6601000e-01
  -1.7429771e+00]
 [ 1.1000000e+01  7.0000000e+00  5.0000000e+00  3.0000000e+00
   2.0000000e+00]
 [ 2.9000000e+01  2.3000000e+01  1.9000000e+01  1.7000000e+01
   1.3000000e+01]
 [ 4.7000000e+01  4.3000000e+01  4.1000000e+01  3.7000000e+01
   3.1000000e+01]
 [ 7.1000000e+01  6.7000000e+01  6.1000000e+01  5.9000000e+01
   5.3000000e+01]
 [ 9.7000000e+01  8.9000000e+01  8.3000000e+01  7.9000000e+01
   7.3000000e+01]]
Indexes dari Element Sorting Descending: [[1 4 2 0 3]
 [1 0 4 3 2]
 [2 0 3 1 4]
 [4 1 2 3 0]
 [4 3 1 2 0]
 [4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]]
